package org.drools.workshop;
import org.drools.workshop.model.*;

rule "Category By Age: Adult"
    when
        $u: User( age >= 18, category == null ||  == "")
    then
        $u.setCategory("Adult");
end

rule "Category By Age: Teenager"
    when
        $u: User( age > 12 && < 18, category == null || == "")
    then
        $u.setCategory("Teenager");
end

rule "Category By Age: Children"
    when
        $u: User( age < 12 && >= 0, category == null || == "")
    then
        $u.setCategory("Children");
end

rule "Category By Age: Not Valid"
    when
        $u: User( age < 0, category == null || == "")
    then
        $u.setCategory("Not Valid");
end

rule "Prender Luz"
  when
    $m: SensorPresencia(presence == true && $m.place==place)
    $r: Home_object($m.place==place)
    $f: Foco($m.place==place)
  then
    $f.setState(true);
end

rule "Apagar Luz"
  when
    $m: SensorPresencia(presence == false && $m.place==place)
    $r: Home_object($m.place==place)
    $f: Foco($m.place==place)
  then
    $f.setState(true);
end

rule "Prender Aire"
    when
        $p: Place()
        $t: SensorTemperatura($t.temperature == $p.max_temp && $t.place == place)
        $a: AireCondicionado($a.place == $t.place)
    then
        $a.setIntensity(30);
 end  

 rule "Prender Calefaccion"
    when
        $p: Place()
        $t: SensorTemperatura($t.temperature == $p.max_temp && $t.place == place)
        $c: Calefaccion($c.place == $t.place)
    then
        $c.setIntensity(30);
 end  








